import type { Metadata } from "next";
import Link from "next/link";
import { Geist_Mono } from "next/font/google";
import "./globals.css";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAV_ITEMS = [
  { path: "/", label: "Add" },
  { path: "/chat", label: "Chat" },
  { path: "/settings", label: "Settings" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body
        className={`${geistMono.variable} font-mono antialiased bg-black text-white min-h-screen flex flex-col`}
      >
        <nav className="border-b border-white/20 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-8">
            <span className="font-bold tracking-tighter text-xl">NoteRAG</span>
            <div className="flex space-x-6">
              {NAV_ITEMS.map((item) => (
                <Link key={item.path} href={item.path}>
                  <span className="text-sm uppercase tracking-widest hover:text-white/70 transition-colors">
                    [{item.label}]
                  </span>
                </Link>
              ))}
            </div>
          </div>
        </nav>
        <main className="flex-grow flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
